### ISSUE TITLE
Improve navigation menu responsiveness

### ISSUE THREAD

**Issue by ansell** [aruizca/jingo#12]
I have a 13 inch retina monitor that is unable to show the tools menu without zooming out twice (Command + -) The behaviour is the same for both Firefox and Safari

Firefox:
<img width="1280" alt="screen shot 2016-02-04 at 8 51 43 am" src="https://cloud.githubusercontent.com/assets/82365/12798340/f20ba42a-cb1c-11e5-981c-bd480a914392.png">

Safari:
<img width="1280" alt="screen shot 2016-02-04 at 8 51 53 am" src="https://cloud.githubusercontent.com/assets/82365/12798373/2c51114c-cb1d-11e5-975b-aa2bd7d04a20.png">

After zooming out twice it appears, along with a shadow box:
<img width="1280" alt="screen shot 2016-02-04 at 8 52 13 am" src="https://cloud.githubusercontent.com/assets/82365/12798358/18b4b4cc-cb1d-11e5-8a0d-202bb68f49a0.png">

**Comment by matthewandrews** [comment]
I think this touches on another problem - the Tools button is really too small given its large role in typical workflow in the wiki.  I would suggest moving it to a more prominent position, perhaps a Tools menu in the top bar.  Could be just left of the username.  (That would also resolve this issue.) @aruizca, are you working on this? If not I'm happy to.

**Comment by aruizca** [comment]
Agree. Please open an issue. The top bar is already pretty crowded and not all screens have the tools button. Let's think about alternative ways

**Comment by matthewandrews** [comment]
Ok created issue #13 for the need to make Tools more prominent.

**Comment by matthewandrews** [comment]
This issue (fixed navbar overlapping top of page including Tools buttons when wrapping beyond one line) is most simply resolved by changing the top navbar to be non-fixed.  This means that the black navbar would be at the top of page content and would scroll out of view when the user scrolls down the page, rather than staying visible at the top at all times; the advantage is that we can have however many nav submenus as we like, wrapping at various browser widths, and the navbar will just wrap without obscuring the Tools buttons or other page content.

The alternative would be to limit the number of nav submenus (probably to fewer than we have right now), and have the navbar revert to a hamburger or other compact version below a threshold (fairly wide) width to avoid any wrapping.

Right now a browser narrower than about 1420px gets a line-wrapped navbar obscuring the Tools buttons, which is really not OK.

**Comment by aruizca** [comment]
I like the first option better. It is just a simple change in a couple of
layout screens.
Ideally I'd like a menu bar that groups 1st level menu items in a parent
one called 'Other' that is displayed depending on the width available and
how the existing menu items fit. This is not just a responsiveness problem
and it requires javascript. Temi has done something similar in the
Biocollect project but did not have enough time to integrate it. This is
not trivial to do because it would mean a three level navigation menu
component. You would also have to change the way the navigation.md is
parsed.

**Comment by aatteia** [comment]
I think the ideal solution is to curate the navigation that limits the number of navigation choices (between 5 and 7 is ideal). It seems to be the easiest option technically (correct me if I am wrong here) and from a UX perspective makes the most sense. The more options the menu has, the more unwieldily/unusable it becomes.

**Comment by aruizca** [comment]
You are right that the navigation menu is not prepared to scale to an
unlimited number of menu items in terms of UX. But in this case the problem
is also technical as even if you limit the number of menu items, at the end
it all comes down to the number of characters in those options. For the
menu items we have at the moment, just making the menu bar not fixed at the
top would solve our current problem. At the end I think it will become
obvious that adding more top level menu items does not work, but at least
we should support that they are shown correctly even if it is not practical.

**Comment by matthewandrews** [comment]
Good point - we could (and perhaps should) do both: change the navbar to be non-fixed, and edit the navigation to reduce the number/length of top level menu items. I'll work on it in test and let you know when it's ready to review.

**Comment by matthewandrews** [comment]
OK, https://jingo-test.ala.org.au/ now has the navbar non-fixed (and I've also fixed the toggle button that looks like a breadcrumb menu for narrower browser windows/phones).

**Comment by aruizca** [comment]
Looks good!

**Comment by matthewandrews** [comment]
OK, released to production: tag 'v1.6.1-ALA-03'.
